### ISSUE TITLE
Pin the openjdk version

### ISSUE THREAD

**Issue by hdelva** [Ontotext-AD/graphdb-docker#21]
The (free) docker image is currently broken before it depends on `adoptopenjdk/openjdk11:alpine`, which always results in the latest version. A recent update in this image has updated the `busybox-extras` package, which breaks line 14 of the Dockerfile; it tries to install `busybox-extras=1.31.1-r20`, which conflicts with the installed `busybox-extras=1.32.1-r6 package`.

As this can keep happening each time the base image gets updated, I would suggest to pin the version number (the current version would `adoptopenjdk/openjdk11:jre-11.0.11_9-alpine`). This version conflict also suggests there's no need to install the `busybox-extras` package at all, it seems to be a part of the base image.

**Comment by nikolaykolev** [comment]
The base image will change even with a fixed version number because adoptopenjdk are updating all images when vulnerabilities in some packages are found. That's why we've added specific busybox-extras version, because of vulnerabilities. So pinning the version won't help, we'll just keep track of such issues and fix them asap. The issue won't happen if the busybox-extras version wasn't pinned like that, but it had to be done, in order to keep the image clean from vulnerabilities.
I've fixed this in https://github.com/Ontotext-AD/graphdb-docker/pull/22
